apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perth-transport-map
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/Accurate0/perth-transport-map.git
    path: kubernetes
    kustomize:
      images:
        - ghcr.io/accurate0/perth-transport-map-api=ghcr.io/accurate0/perth-transport-map-api:${ARGOCD_APP_REVISION}
        - ghcr.io/accurate0/perth-transport-map-web=ghcr.io/accurate0/perth-transport-map-web:${ARGOCD_APP_REVISION}
        - ghcr.io/accurate0/perth-transport-map-worker=ghcr.io/accurate0/perth-transport-map-worker:${ARGOCD_APP_REVISION}

  destination:
    server: https://kubernetes.default.svc
    namespace: perth-transport-map
operation:
  initiatedBy:
    username: github-actions
  sync:
    prune: true
    syncStrategy:
      hook: {}
