version: "3.8"
services:
  perthtransport-api:
    env_file:
      - .env
    build:
      dockerfile: ./perthtransport-api/Dockerfile
    container_name: perthtransport-api
    environment:
      - PTA_REDIS_CONNECTION_STRING
      - PTA_WORKER_API_BASE=http://worker:8000/v1
      - PTA_REALTIME_API_KEY
      - PTA_REFERENCE_DATA_API_KEY
      - RUST_LOG
    links:
      - perthtransport-worker:worker
    ports:
      - 8000:8000

  perthtransport-worker:
    env_file:
      - .env
    build:
      dockerfile: ./perthtransport-worker/Dockerfile
    container_name: perthtransport-worker
    environment:
      - PTA_REALTIME_API_KEY
      - PTA_REFERENCE_DATA_API_KEY
      - PTA_REDIS_CONNECTION_STRING
      - RUST_LOG
