version: '3.8'
services:
  perthtransport-api:
    env_file:
      - .env
    build:
      dockerfile: ./perthtransport-api/Dockerfile
      args:
        BUILD_MODE: dev
        BUILD_DIRECTORY: debug
    container_name: perthtransport-api
    environment:
      - PTA_REDIS_CONNECTION_STRING=redis://redis-connection
      - RUST_LOG
    depends_on:
      - redis
    links:
      - redis:redis-connection
    ports:
      - 8000:8000

  perthtransport-worker:
    env_file:
      - .env
    build:
      dockerfile: ./perthtransport-worker/Dockerfile
      args:
        BUILD_MODE: dev
        BUILD_DIRECTORY: debug
    container_name: perthtransport-worker
    environment:
      - PTA_REDIS_CONNECTION_STRING=redis://redis-connection
      - RUST_LOG
    depends_on:
      - redis
    links:
      - redis:redis-connection

  redis:
    image: redis:alpine
    container_name: redis
