version: "3.8"
services:
  perthtransport-api:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      args:
        - BINARY_NAME=perthtransport-api
    container_name: perthtransport-api
    environment:
      - PTA_REDIS_CONNECTION_STRING=redis://redis-connection
      - PTA_WORKER_API_BASE=http://worker:8001/v1
      - PTA_REALTIME_API_KEY
      - PTA_REFERENCE_DATA_API_KEY
      - RUST_LOG
    depends_on:
      - redis
    links:
      - redis:redis-connection
      - perthtransport-worker:worker
    ports:
      - 8000:8000

  perthtransport-worker:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      args:
        - BINARY_NAME=perthtransport-worker
    container_name: perthtransport-worker
    environment:
      - PTA_REALTIME_API_KEY
      - PTA_REFERENCE_DATA_API_KEY
      - PTA_REDIS_CONNECTION_STRING=redis://redis-connection
      - RUST_LOG
    depends_on:
      - redis
    links:
      - redis:redis-connection

  redis:
    image: redis:alpine
    container_name: redis
