app = "pta-worker"
primary_region = "syd"

[build]
image = "ghcr.io/Accurate0:pta-worker"
# dockerfile = "./pta-worker/Dockerfile"

[env]
PTA_REDIS_CONNECTION_STRING = "redis://syd.pta-redis.internal"
