app = "perthtransport-api"
primary_region = "syd"

[build]
image = "ghcr.io/Accurate0:pta-api"
# dockerfile = "./perthtransport-api/Dockerfile"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 1

[checks]
[checks.system_health]
grace_period = "10s"
interval = "60s"
method = "get"
path = "/v1/status/health"
port = 8000
timeout = "10s"
type = "http"

[env]
PTA_REDIS_CONNECTION_STRING = "redis://syd.perthtransport-redis.internal"
