apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: perth-transport-map-secret
  namespace: perth-transport-map
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 900
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: perth-transport-map-41-jp
        envSlug: prod
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: perth-transport-map-managed-secrets
      secretNamespace: perth-transport-map
      creationPolicy: "Owner"
