apiVersion: v1
kind: Service
metadata:
  name: perth-transport-map
  namespace: perth-transport-map
spec:
  selector:
    app: perth-transport-map
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 8001
      targetPort: 8001
    - protocol: TCP
      port: 8000
      targetPort: 8000
