apiVersion: apps/v1
kind: Deployment
metadata:
  name: perth-transport-map-web
  namespace: perth-transport-map
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: perth-transport-map-web
  replicas: 2
  template:
    metadata:
      labels:
        app: perth-transport-map-web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: perth-transport-map-web
              topologyKey: kubernetes.io/hostname
      containers:
        - name: perth-transport-map-web
          image: ghcr.io/accurate0/perth-transport-map-web:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: perth-transport-map-managed-secrets
          ports:
            - containerPort: 3000
