name: build-and-push-image
on:
  workflow_call:
    inputs:
      image-name:
        type: string
        required: true
    secrets:
      registry:
        required: true
      AWS_DEPLOY_ROLE_ARN:
        required: true

jobs:
  build-and-push-image:
    name: ${{ inputs.image-name }}
    runs-on: ubuntu-latest

    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.registry }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./${{ inputs.image-name }}/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ secrets.registry }}
          platforms: linux/arm64,arm64/v8
