on:
  workflow_dispatch:

jobs:
  clear-cache:
    name: Delete all caches
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
