name: deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io

jobs:
  build-api:
    uses: ./.github/workflows/build-and-push-image.yaml
    permissions:
      contents: read
      packages: write
    with:
      image-name: perthtransport-api
    secrets: inherit

  build-worker:
    uses: ./.github/workflows/build-and-push-image.yaml
    permissions:
      contents: read
      packages: write
    with:
      image-name: perthtransport-worker
    secrets: inherit

  build-web:
    defaults:
      run:
        working-directory: perthtransport-web

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: perthtransport-web
          path: perthtransport-web/.vercel/output

  deploy-api:
    needs:
      - build-api
      - build-worker
      - build-web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy
        run: flyctl deploy --config ./fly.api.toml --wait-timeout 300
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-worker:
    needs:
      - build-api
      - build-worker
      - build-web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy
        run: flyctl deploy --config ./fly.worker.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-web:
    needs:
      - build-api
      - build-worker
      - build-web
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: perthtransport-web
          path: ./.vercel/output

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
