name: deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io

jobs:
  build-pta-api:
    uses: ./.github/workflows/build-and-push-image.yaml
    permissions:
      contents: read
      packages: write
    with:
      image-name: pta-api
    secrets: inherit

  build-pta-worker:
    uses: ./.github/workflows/build-and-push-image.yaml
    permissions:
      contents: read
      packages: write
    with:
      image-name: pta-worker
    secrets: inherit

  deploy-pta-api:
    needs: build-pta-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: build & deploy
        run: flyctl deploy --config ./fly.api.toml --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-pta-worker:
    needs: build-pta-worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: build & deploy
        run: flyctl deploy --config ./fly.worker.toml --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
