name: deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  build-api:
    uses: ./.github/workflows/build-and-push-image.yaml
    permissions:
      id-token: write
    with:
      image-name: perthtransport-api
      registry: ${{ vars.AWS_ECR_API_REGISTRY }}
    secrets: inherit

  build-worker:
    uses: ./.github/workflows/build-and-push-image.yaml
    permissions:
      id-token: write
    with:
      image-name: perthtransport-worker
      registry: ${{ vars.AWS_ECR_WORKER_REGISTRY }}
    secrets: inherit

  build-web:
    defaults:
      run:
        working-directory: perthtransport-web

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: perthtransport-web
          path: ./perthtransport-web/.vercel/output
          if-no-files-found: "error"

  deploy-ecs:
    needs:
      - build-api
      - build-worker
      - build-web
    runs-on: ubuntu-latest
    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: deploy container
        run: aws ecs update-service --region ${{ vars.AWS_REGION }} --cluster default-cluster --service perthtransport-service --force-new-deployment 2>&1 1>/dev/null

  deploy-web:
    needs:
      - build-api
      - build-worker
      - build-web
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: perthtransport-web
          path: ./.vercel/output

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
