name: deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  pta-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: build & deploy
        run: flyctl deploy --config ./fly.api.toml --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  pta-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: build & deploy
        run: flyctl deploy --config ./fly.worker.toml --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
